name: IDL2DDS Compose Runner

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-idl2dds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (required even if empty repo)
        uses: actions/checkout@v4

      - name: Clone IDL2DDS repository
        run: |
          git clone https://github.com/MCO-PICCOLO/IDL2DDS -b master

      - name: Install Docker and Compose
        run: |
            echo "ðŸ³ Installing Docker CLI and Docker Compose..."
            sudo apt-get update -y
            sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

            UBUNTU_CODENAME=$(lsb_release -cs)
            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu $UBUNTU_CODENAME stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update
            sudo apt-get install -y \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin \
            docker-compose-plugin

            docker --version
            docker compose version

      - name: Run IDL2DDS using docker compose
        working-directory: ./IDL2DDS
        run: |
          docker compose up -d --build

      - name: Check if IDL2DDS container is healthy
        run: |
          docker ps -a
          docker logs idl2dds || true

      - name: Wait for IDL2DDS container readiness
        run: |
          for i in {1..5}; do
            if curl -sf http://localhost:12345/health; then
              echo "âœ… IDL2DDS is ready!"
              break
            else
              echo "âŒ› Waiting for IDL2DDS container... ($i)"
              sleep 2
            fi
          done
